### ISSUE TITLE
モデル構成

### ISSUE THREAD

**Issue by kota-1248** [kota-1248/Portfolio-admin#4]
# テーブル一覧（論理名、物理名）
論理名:skillCategories
物理名:skills

# 各テーブルのテーブル定義（DDL）
CREATE TABLE skills (
id int(255) NOT NULL AUTO_INCREMENT,
category varchar(255) DEFAULT NULL,
name varchar(255) DEFAULT NULL,
score int(255) DEFAULT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

# カラム一覧（データ型、外部キー・ユニーク制約など含む情報）（論理名、物理名共に）
論理名:カテゴリー
物理名:category
データ型: varchar(225)
default制約：null

論理名:言語
物理名:name
データ型 : varchar(255)
default制約：null

論理名:スコア
物理名:score
(論理名)/ スコア(物理名)
データ型 : int(255)
default制約：null

論理名:スキルID
データ型 : int(255)
not null制約
prymary制約

・スキル情報を取得するSQLとその結果
<img width="328" alt="スクリーンショット 2020-04-30 13 42 51" src="https://user-images.githubusercontent.com/62986276/80673074-4b167f00-8ae9-11ea-9ce5-a37f83647ffb.png">
<img width="328" alt="スクリーンショット 2020-04-30 13 42 40" src="https://user-images.githubusercontent.com/62986276/80673080-4fdb3300-8ae9-11ea-8093-e79dab06a1e9.png">
<img width="328" alt="スクリーンショット 2020-04-30 13 44 08" src="https://user-images.githubusercontent.com/62986276/80673122-713c1f00-8ae9-11ea-81df-ec0f88dd599d.png">
<img width="328" alt="スクリーンショット 2020-04-30 13 44 15" src="https://user-images.githubusercontent.com/62986276/80673135-79945a00-8ae9-11ea-943b-60fe31a8d0ce.png">
<img width="328" alt="スクリーンショット 2020-04-30 13 45 54" src="https://user-images.githubusercontent.com/62986276/80673355-0e975300-8aea-11ea-9bd0-ca24cdbbd03d.png">
<img width="328" alt="スクリーンショット 2020-04-30 13 45 48" src="https://user-images.githubusercontent.com/62986276/80673381-12c37080-8aea-11ea-95c3-d5aeaf165a81.png">

**Comment by hidekishibashi** [comment]
>論理名:skillCategories
物理名:skills

これはどういうこと？

>id int(255) NOT NULL AUTO_INCREMENT,

intで大丈夫かと

>論理名:スコア
物理名:score
(論理名)/ スコア(物理名)
データ型 : int(255)
default制約：null

>論理名:スキルID
データ型 : int(255)
not null制約
prymary制約

このあたり見直してください。
